name: Build

on:
  push:
    branches:
      - main
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    
    - name: Apply patches
      run: ./patch.sh

    - name: Build gpsinfo
      run: ./build.sh harbour-gpsinfo

    - name: Build systemmonitor
      run: ./build.sh harbour-systemmonitor

    - name: Build bikeme
      run: ./build.sh harbour-bikeme

    - name: Upload build result
      uses: actions/upload-artifact@v2
      with:
        name: rpms
        path: RPMS

    - name: Create release
      if: startsWith(github.ref, 'refs/tags/')
      uses: ncipollo/release-action@v1
      with:
        artifacts: "RPMS/*.rpm"
        token: ${{ secrets.GITHUB_TOKEN }}
